import { StyleSheet } from 'react-native';
import Color from '../../../utils/Color';
import { moderateScale, scale, verticalScale } from '../../../utils/Responsive';
import { Fonts } from '../../../utils/Font';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Color.White },
  profileImage: {
    width: scale(80),
    height: scale(80),
    alignSelf: 'center',
    marginTop: scale(15),
    marginBottom: scale(10),
    borderRadius: scale(40),
  },
  userName: {
    fontSize: moderateScale(17),
    textAlign: 'center',
    fontFamily: Fonts.interBold,
    color: Color.Black,
  },
  form: { margin: scale(15) },
  heading: {
    fontSize: scale(16),
    fontFamily: Fonts.interSemiBold,
    color: Color.Black,
  },
  inputStyle: {
    fontSize: scale(14),
    fontFamily: Fonts.interRegular,
    backgroundColor: Color.fieldColor,
    marginTop: verticalScale(8),
    marginBlock: verticalScale(12),
    borderRadius: scale(16),
    height: verticalScale(46),
  },
  devider: {
    height: verticalScale(1),
    backgroundColor: Color.rgba.Gray[2],
    marginTop: verticalScale(3),
    marginBottom: verticalScale(18),
  },
  text: {
    fontSize: moderateScale(14),
    color: Color.rgba.Black[6],
    fontFamily: Fonts.interRegular,
    lineHeight: verticalScale(20),
    paddingVertical: verticalScale(5),
    paddingBottom: verticalScale(17),
  },
  absolute: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
  videoIcon: { width: scale(24), height: scale(24) },
  introVideoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  videoImage: {
    width: scale(343),
    height: scale(343),
    borderRadius: scale(16),
    marginVertical: verticalScale(12),
    marginBottom: verticalScale(18),
  },
  questionnaireHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  editIcon: { width: scale(24), height: scale(24), marginRight: scale(15) },
  downArrowIcon: { width: scale(24), height: scale(24) },
  questionnaireView: { marginTop: verticalScale(15) },
  questionContainer: {
    marginBottom: verticalScale(20),
  },
  questionText: {
    fontSize: moderateScale(14),
    marginBottom: verticalScale(12),
    fontFamily: Fonts.interRegular,
    lineHeight: verticalScale(20),
  },
  optionsRow: {
    flexDirection: 'row',
    gap: scale(10),
  },
  optionButton: {
    borderRadius: scale(16),
    backgroundColor: Color.fieldColor,
    width: scale(93),
    height: verticalScale(30),
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionButtonSelected: {
    borderWidth: scale(1),
    borderColor: Color.theme1,
    backgroundColor: Color.rgba.theme1[1],
  },
  optionText: {
    fontSize: moderateScale(12),
    color: Color.Black,
  },
  optionTextSelected: {
    color: Color.Black,
    fontFamily: Fonts.interRegular,
  },
  subscriptionTitle: {
    fontSize: moderateScale(24),
    color: Color.Black,
    fontFamily: Fonts.interSemiBold,
    textAlign: 'center',
  },
  subscriptionContainer: { marginTop: verticalScale(13) },
  subscriptionView: {
    width: scale(111),
    height: verticalScale(111),
    borderRadius: scale(12),
    borderWidth: scale(1),
    borderColor: Color.rgba.Gray[2],
    marginRight: scale(5),
    marginBottom: verticalScale(5),
  },
  subscriptionPrice: {
    fontSize: scale(17),
    fontFamily: Fonts.sfProRegular,
    color: Color.Black,
    width: scale(48),
    height: verticalScale(30),
    borderWidth: scale(1),
    borderColor: Color.rgba.Gray[2],
    borderRadius: scale(7),
    textAlign: 'center',
    alignSelf: 'center',
    marginTop: verticalScale(8),
  },
  subscriptionImage: {
    width: scale(40),
    height: scale(40),
    alignSelf: 'center',
  },
  subscriptionName: {
    fontSize: moderateScale(12),
    fontFamily: Fonts.interMedium,
    textAlign: 'center',
  },
  profileRow: { flexDirection: 'row', gap: scale(10) },
  selectedScriptionImage: { width: scale(24), height: scale(24) },
  profileName: {
    fontSize: scale(16),
    color: Color.Black,
    fontFamily: Fonts.interRegular,
  },
  referalDetailView: {
    marginTop: verticalScale(15),
    marginBottom: verticalScale(25),
  },
  referalView: {
    width: scale(157),
    height: verticalScale(48),
    borderRadius: scale(16),
    backgroundColor: Color.rgba.Gray[1],
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: scale(20),
  },
  referalText: {
    fontSize: scale(14),
    color: Color.Black,
    fontFamily: Fonts.interRegular,
  },
  Icon: { width: scale(24), height: scale(24) },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  totalReferalText: {
    fontSize: moderateScale(12),
    color: Color.Black,
    fontFamily: Fonts.interMedium,
  },
  totalReferalView: {
    width: scale(50),
    height: verticalScale(48),
    backgroundColor: Color.rgba.Gray[1],
    borderRadius: scale(16),
    alignItems: 'center',
    justifyContent: 'center',
  },
  totalReferalValue: {
    fontSize: moderateScale(14),
    fontFamily: Fonts.interSemiBold,
  },
  inviteColumnStyle: {
    justifyContent: 'space-around',
    marginBottom: verticalScale(15),
  },
  inviteView: {
    alignItems: 'center',
  },
  inviteIconView: {
    width: scale(50),
    height: scale(50),
    borderRadius: scale(25),
    backgroundColor: Color.rgba.Gray[1],
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: verticalScale(15),
  },
  inviteIcon: { width: scale(27), height: scale(26) },
  inviteText: {
    fontSize: scale(12),
    color: Color.Black,
    fontFamily: Fonts.interRegular,
    paddingTop: verticalScale(5),
    textAlign: 'center',
  },
  reffralInputView: { marginTop: verticalScale(20) },
  referalInputStyle: {
    width: scale(157),
    height: verticalScale(48),
    backgroundColor: Color.rgba.Gray[1],
    color: Color.Gray,
    borderRadius: scale(16),
    marginVertical: verticalScale(10),
    marginRight: scale(10),
  },
  singleGrid: {
    width: scale(167),
    height: verticalScale(70),
    backgroundColor: Color.White,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: scale(16),
  },
  refferalBadgeView: {
    height: verticalScale(106),
    width: scale(343),
    backgroundColor: 'Color.White',
    borderRadius: scale(20),
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  refferalCountView: {
    alignItems: 'center',
    marginHorizontal: scale(18),
    alignSelf: 'center',
    gap: scale(5),
    // marginVertical: verticalScale(12),
  },
  refferalCount: {
    fontSize: scale(12),
    fontFamily: Fonts.interSemiBold,
    color: Color.Black,
  },
  infoIconBtn: { position: 'absolute', right: 0, top: verticalScale(12) },
  infoIcon: {
    width: scale(20),
    height: scale(20),
  },
  bottomTab: { marginVertical: verticalScale(15), marginRight: scale(2) },
});
