export const Api = {
  sendOtp: 'send/otp',
  verifyOtp: 'verify/otp',
  signUp: 'signUp',
  login: 'login',
  forgotPassword: 'forgot/password',
  uploadProfileImage: 'profile/image/upload',
  saveAccount: 'profile/setup',
  getProfileData: 'profile',
  uploadIntroVideo: 'profile/video/upload',
  gathering: 'gathering',
  uploadGroupPicture: 'gathering/profile/upload',
  saveGathering: '/gathering/save',
  removeAllGetherings: 'gathering/save/all',
  getSavedGatherings: 'gathering/save',
  community: 'community',
};
