// export const Images = {
//   chatIcon: require('../assets/image/chat.png'),
//   darkChatIcon: require('../assets/image/darkChat.png'),
//   searchIcon: require('../assets/image/search.png'),
//   darkSearchIcon: require('../assets/image/darkSearch.png'),
//   gridcon: require('../assets/image/grid.png'),
//   darkGridcon: require('../assets/image/darkGrid.png'),
//   profileIcon: require('../assets/image/profile.png'),
//   darkProfileIcon: require('../assets/image/darkProfile.png'),
//   gpsMobileImage: require('../assets/image/gpsMobile.png'),
//   appleIcon: require('../assets/image/apple.png'),
//   googleIcon: require('../assets/image/google.png'),
//   forgotPasswordIcon: require('../assets/image/password.png'),
//   profileImageIcon: require('../assets/image/account.png'),
//   profileImageIcon1: require('../assets/image/profileImageIcon.png'),
//   plusIcon: require('../assets/image/plus.png'),
//   cameraIcon: require('../assets/image/camera.png'),
//   languageIcon: require('../assets/image/language.png'),
//   editIcon: require('../assets/image/edit.png'),
//   videoIcon: require('../assets/image/video.png'),
//   videoImage: require('../assets/image/videoImage.png'),
//   downArrowImage: require('../assets/image/downArrow.png'),
//   heartIcon: require('../assets/image/heartIcon.png'),
//   copyIcon: require('../assets/image/copy.png'),
//   copyIcon1: require('../assets/image/copy1.png'),
//   whatsappIcon: require('../assets/image/whatsapp.png'),
//   telegramIcon: require('../assets/image/telegram.png'),
//   telegramIcon1: require('../assets/image/telegram1.png'),
//   messageIcon: require('../assets/image/message.png'),
//   twitterIcon: require('../assets/image/twitter.png'),
//   facebookIcon: require('../assets/image/facebook.png'),
//   rightTickIcon: require('../assets/image/rightTick.png'),
//   supportIcon: require('../assets/image/support.png'),
//   termsAndPrivacyIcon: require('../assets/image/termsAndPrivacy.png'),
//   logoutIcon: require('../assets/image/logout.png'),
//   refferalBadgesIcon: require('../assets/image/refferalBadges.png'),
//   informationIcon: require('../assets/image/info.png'),
//   rightIcon: require('../assets/image/right.png'),
//   switchIcon: require('../assets/image/switchIcon.png'),
//   lsitViewIcon: require('../assets/image/infoIcon.png'),
//   mapViewIcon: require('../assets/image/infoIcon1.png'),
//   unsavedIcon: require('../assets/image/unsavedIcon.png'),
//   infoIcon: require('../assets/image/informationIcon.png'),
//   createIcon: require('../assets/image/createIcon.png'),
//   filterIcon: require('../assets/image/filterIcon.png'),
//   localImage: require('../assets/image/localImage.png'),
//   onlineImage: require('../assets/image/onlineImage.png'),
//   savedAllIcon: require('../assets/image/savedAllIcon.png'),
//   removedAllIcon: require('../assets/image/removedAllIcon.png'),
//   checkIcon: require('../assets/image/checkIcon.png'),
//   searchIcon1: require('../assets/image/searchIcon1.png'),
//   plusFabIcon: require('../assets/image/plusFabIcon.png'),
//   groupPictureImageIcon: require('../assets/image/groupPictureIcon.png'),
//   uploadImageIcon: require('../assets/image/uploadImage.png'),
//   precizeLocationImage: require('../assets/image/precizeLocationImage.png'),
//   approximateLocationImage: require('../assets/image/approximateLocationImage.png'),
//   userGroupImageIcon: require('../assets/image/userGroupImageIcon.png'),
//   musicImage: require('../assets/image/musicImage.png'),
//   bibleStudyImage: require('../assets/image/bibleStudyImage.png'),
//   outDorsImage: require('../assets/image/outDorsImage.png'),
//   milesImage: require('../assets/image/milesImage.png'),
//   userIcon: require('../assets/image/user.png'),
//   removeIcon: require('../assets/image/removeIcon.png'),
//   savedIcon: require('../assets/image/savedIcon.png'),
//   publikHelpImage: require('../assets/image/publikHelpImage.png'),
//   fullServiceImage: require('../assets/image/fullServiceImage.png'),
//   casualImage: require('../assets/image/casualImage.png'),
//   evangelismImage: require('../assets/image/evangelismImage.png'),
//   outDorsImage1: require('../assets/image/outDorsImage1.png'),
//   homeImage: require('../assets/image/homeImage.png'),
//   churchImage: require('../assets/image/churchImage.png'),
//   otherImage: require('../assets/image/otherImage.png'),
//   approxLocationtypeImage: require('../assets/image/approxLocationTypeImage.png'),
//   presizeLocationtypeImage: require('../assets/image/precizeLocationtypeImage.png'),
//   referalImage1: require('../assets/image/referalImage1.png'),
//   referalImage2: require('../assets/image/referalImage2.png'),
//   referalImage3: require('../assets/image/referalImage3.png'),
//   referalImage4: require('../assets/image/referalImage4.png'),
//   referalImage5: require('../assets/image/referalImage5.png'),
//   locationScanningImage: require('../assets/image/locationScanningImage.png'),
//   threedotCircleImage: require('../assets/image/threedotCircleImage.png'),
//   locationIconImage: require('../assets/image/locationIconImage.png'),
// };

export const Images = {
  appleIcon: require('../assets/image/apple.png'),
  approximateLocationImage: require('../assets/image/approximateLocationImage.png'),
  approxLocationtypeImage: require('../assets/image/approxLocationTypeImage.png'),

  bibleStudyImage: require('../assets/image/bibleStudyImage.png'),

  cameraIcon: require('../assets/image/camera.png'),
  casualImage: require('../assets/image/casualImage.png'),
  chatIcon: require('../assets/image/chat.png'),
  checkIcon: require('../assets/image/checkIcon.png'),
  churchImage: require('../assets/image/churchImage.png'),
  copyIcon: require('../assets/image/copy.png'),
  copyIcon1: require('../assets/image/copy1.png'),
  createIcon: require('../assets/image/createIcon.png'),

  darkChatIcon: require('../assets/image/darkChat.png'),
  darkGridcon: require('../assets/image/darkGrid.png'),
  darkProfileIcon: require('../assets/image/darkProfile.png'),
  darkSearchIcon: require('../assets/image/darkSearch.png'),
  downArrowImage: require('../assets/image/downArrow.png'),

  editIcon: require('../assets/image/edit.png'),
  evangelismImage: require('../assets/image/evangelismImage.png'),

  facebookIcon: require('../assets/image/facebook.png'),
  filterIcon: require('../assets/image/filterIcon.png'),
  forgotPasswordIcon: require('../assets/image/password.png'),
  fullServiceImage: require('../assets/image/fullServiceImage.png'),

  googleIcon: require('../assets/image/google.png'),
  gpsMobileImage: require('../assets/image/gpsMobile.png'),
  gridcon: require('../assets/image/grid.png'),
  groupPictureImageIcon: require('../assets/image/groupPictureIcon.png'),

  heartIcon: require('../assets/image/heartIcon.png'),
  homeImage: require('../assets/image/homeImage.png'),

  informationIcon: require('../assets/image/info.png'),
  infoIcon: require('../assets/image/informationIcon.png'),

  languageIcon: require('../assets/image/language.png'),
  localImage: require('../assets/image/localImage.png'),
  locationIconImage: require('../assets/image/locationIconImage.png'),
  locationScanningImage: require('../assets/image/locationScanningImage.png'),
  logoutIcon: require('../assets/image/logout.png'),
  lsitViewIcon: require('../assets/image/infoIcon.png'),

  mapViewIcon: require('../assets/image/infoIcon1.png'),
  messageIcon: require('../assets/image/message.png'),
  milesImage: require('../assets/image/milesImage.png'),
  musicImage: require('../assets/image/musicImage.png'),

  onlineImage: require('../assets/image/onlineImage.png'),
  otherImage: require('../assets/image/otherImage.png'),
  outDorsImage: require('../assets/image/outDorsImage.png'),
  outDorsImage1: require('../assets/image/outDorsImage1.png'),

  plusFabIcon: require('../assets/image/plusFabIcon.png'),
  plusIcon: require('../assets/image/plus.png'),
  precizeLocationImage: require('../assets/image/precizeLocationImage.png'),
  presizeLocationtypeImage: require('../assets/image/precizeLocationtypeImage.png'),
  profileIcon: require('../assets/image/profile.png'),
  profileImageIcon: require('../assets/image/account.png'),
  profileImageIcon1: require('../assets/image/profileImageIcon.png'),
  publikHelpImage: require('../assets/image/publikHelpImage.png'),

  referalImage1: require('../assets/image/referalImage1.png'),
  referalImage2: require('../assets/image/referalImage2.png'),
  referalImage3: require('../assets/image/referalImage3.png'),
  referalImage4: require('../assets/image/referalImage4.png'),
  referalImage5: require('../assets/image/referalImage5.png'),
  refferalBadgesIcon: require('../assets/image/refferalBadges.png'),
  removeIcon: require('../assets/image/removeIcon.png'),
  rightIcon: require('../assets/image/right.png'),
  rightTickIcon: require('../assets/image/rightTick.png'),

  savedAllIcon: require('../assets/image/savedAllIcon.png'),
  savedIcon: require('../assets/image/savedIcon.png'),
  savedIconFill: require('../assets/image/savedIconFill.png'),
  searchIcon: require('../assets/image/search.png'),
  searchIcon1: require('../assets/image/searchIcon1.png'),
  supportIcon: require('../assets/image/support.png'),
  switchIcon: require('../assets/image/switchIcon.png'),

  telegramIcon: require('../assets/image/telegram.png'),
  telegramIcon1: require('../assets/image/telegram1.png'),
  termsAndPrivacyIcon: require('../assets/image/termsAndPrivacy.png'),
  threedotCircleImage: require('../assets/image/threedotCircleImage.png'),
  twitterIcon: require('../assets/image/twitter.png'),

  unsavedIcon: require('../assets/image/unsavedIcon.png'),
  uploadImageIcon: require('../assets/image/uploadImage.png'),
  userGroupImageIcon: require('../assets/image/userGroupImageIcon.png'),
  userIcon: require('../assets/image/user.png'),

  videoIcon: require('../assets/image/video.png'),
  videoImage: require('../assets/image/videoImage.png'),

  whatsappIcon: require('../assets/image/whatsapp.png'),

  // chat
  chatLocationIcon: require('../assets/image/chatLocation.png'),
  chatNotificationIcon: require('../assets/image/chatNotification.png'),
  chatMultiuserIcon: require('../assets/image/chatMultiuser.png'),
  calenderIcon: require('../assets/image/calender.png'),
  pinIcon: require('../assets/image/pinIcon.png'),
  leaveIcon: require('../assets/image/leaveIcon.png'),
  reportIcon: require('../assets/image/report.png'),
  deleteIcon: require('../assets/image/deleteIcon.png'),
  blockIcon: require('../assets/image/blockIcon.png'),
};
